Make mandatory elements mandatory
ebu/ebu-tt-xsd pull request #22
Opened 2019-06-21 13:14 UTC by nigelmegitt

Make the following mandatory elements' cardinality:
* `tt:styling`
* `tt:layout`
* `tt:region`
* `tt:div`

Also describe a style guide in the README where if non-default `minOccurs` or `maxOccurs` values are used, _both_ attributes should be specified.

2019-06-21 13:18 UTC, nigelmegitt commented
This may also close #9.

2019-06-21 13:48 UTC, nigelmegitt commented
Now also closes #12.

2019-06-24 14:14 UTC, spoeschel commented on README.md
> +_both_ attribtues should be specified.
```suggestion
_both_ attributes should be specified.
```

2019-06-24 14:17 UTC, spoeschel commented on ebutt.xsd
> +			<xs:element name="region" type="tt:region"  minOccurs="1" maxOccurs="unbounded"/>
```suggestion
			<xs:element name="region" type="tt:region" minOccurs="1" maxOccurs="unbounded"/>
```

2019-06-24 14:19 UTC, spoeschel commented on ebutt.xsd
>  			<xs:element name="style" type="tt:style" maxOccurs="unbounded"/>
```suggestion
			<xs:element name="style" type="tt:style" minOccurs="1" maxOccurs="unbounded"/>
```

2019-06-24 14:25 UTC, spoeschel requested changes
Thank you! I just suggested some small fixes.

2019-06-25 09:48 UTC, nigelmegitt commented
Thank you, all those changes accepted.

2019-06-25 10:45 UTC, spoeschel approved these changes

2019-06-25 14:16 UTC, merged